config/routes.rb
Rails.application.routes.draw do
  resources :comments
  get 'dashboard/index'

  get 'users/index'

  devise_for :users, controllers: {
      sessions: "users/sessions",
      registrations: 'registrations',
      omniauth_callbacks: "users/omniauth_callbacks" 
  }
  resources :users do  
    resources :user_interests
  end

  get 'landings/welcome'
  
  get 'request_applies/index'

  get  'requests/index'  
  get  'requests/new'
  get  'requests/disabled'
  post 'requests/create'
  get  'requests/:id_request' , to:'requests#show' , as:'requests_detail'
  get  'requests/accepted_request', to:'requests#accepted_request' , as:'accepted_request'

  get  'request_applies/accepted_applies'
  post 'request_applies/apply/:id_request', to:'request_applies#new',  as:'apply'

  patch 'request_applies/rechazo_apply/:id_request_apply', to: 'request_applies#revoke_apply', as: 'rechazo'
  post 'request_applies/accept_apply/:id_request_apply', to: 'request_applies#accept_apply', as: 'accept_apply'

  root 'landings#welcome'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :request
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_action :set_user  
  before_action :set_request

  # GET /comments
  # GET /comments.json

  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create

    @comment = Comment.new(comment_params)    

    @comment.user_id = @user.id
    @comment.request_id = @request.id

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
        format.js
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end
    def set_user
      @user = current_user
    end
    def set_request
      @request = Request.find(params[:request_id_f])      
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:contenido, :user_id, :request_id)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<tr>
    <td><%= comment.contenido %></td>
    <td><%= comment.user.name %></td>
    <td><%= comment.request.title %></td>            
</tr>

app/views/comments/_form.html.erb
<% @comment = Comment.new %>
<%= form_for(@comment, remote: true) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :contenido %><br>
    <%= f.text_area :contenido %>
    <%= hidden_field_tag "request_id_f", @request.id %>
  </div>  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/_index.html.erb
<p id="notice"><%= notice %></p>

<table>
  <thead>
    <tr>
      <th>Contenido</th>
      <th>User</th>
      <th>Request</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody id="comments">
    <% @comments.each do |comment| %>
      <%= render comment %>
    <% end %>
  </tbody>
</table>

<br>

app/views/comments/create.js.erb
$("#comments").append("<%= j render @comment %>")

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Contenido:</strong>
  <%= @comment.contenido %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user %>
</p>

<p>
  <strong>Request:</strong>
  <%= @comment.request %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>