config/routes.rb
Rails.application.routes.draw do
  resources :comments
  get 'dashboard/index'

  get 'users/index'

  devise_for :users, controllers: {
      sessions: "users/sessions",
      registrations: 'registrations',
      omniauth_callbacks: "users/omniauth_callbacks" 
  }
  resources :users do  
    resources :user_interests
  end

  get 'landings/welcome'
  
  get 'request_applies/index'

  get  'requests/index'  
  get  'requests/new'
  get  'requests/disabled'
  post 'requests/create'
  get  'requests/:id_request' , to:'requests#show' , as:'requests_detail'
  get  'requests/accepted_request', to:'requests#accepted_request' , as:'accepted_request'

  get  'request_applies/accepted_applies'
  post 'request_applies/apply/:id_request', to:'request_applies#new',  as:'apply'

  patch 'request_applies/rechazo_apply/:id_request_apply', to: 'request_applies#revoke_apply', as: 'rechazo'
  post 'request_applies/accept_apply/:id_request_apply', to: 'request_applies#accept_apply', as: 'accept_apply'

  root 'landings#welcome'

end

app/models/user_interest.rb
class UserInterest < ActiveRecord::Base
  belongs_to :user
  belongs_to :interest
end

app/controllers/user_interests_controller.rb
class UserInterestsController < ApplicationController
	def index
		@user = User.find(params[:user_id])
		@user_interests  = @user.interests
		@interests = Interest.all - @user_interests  

	end

	def destroy
		
		@interest = Interest.find(params[:id])
		@user = User.find(params[:user_id])

		@user_interest = UserInterest.find_by(user:@user,interest:@interest)
		@user_interest.destroy
		redirect_to user_user_interests_path(@user)

	end

	def create
		@user = User.find(params[:user_id])
		@user_interest = UserInterest.new(user_interest_params)
		@user_interest.save
		redirect_to user_user_interests_path(@user)

	end

	private

	def user_interest_params
    	params.require(:user_interest).permit(:interest_id,:user_id)
    end
end

app/views/user_interests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing User interest</h1>
  
<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_interests.each do |user_interest| %>
      <tr>
        <td><%= user_interest.name  %></td>
        <td><%= link_to 'Destroy', user_user_interest_path(@user,user_interest), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>
<h1>Listing Interests</h1>
  <tbody>
    <% @interests.each do |interest| %>
      <tr>
        <td><%= interest.name  %></td>

        <td>
        <%= form_for [@user, UserInterest.new] do |f| %>
            <%= f.submit("agregar", class: "btn btn-default") %>
            <%= f.hidden_field(:interest_id, value: interest.id) %>
            <%= f.hidden_field(:user_id, value: @user.id) %>
        
        <% end %>
        </td>
        
        
      </tr>
    <% end %>
  </tbody>
</table>