config/routes.rb
Rails.application.routes.draw do
  resources :comments
  get 'dashboard/index'

  get 'users/index'

  devise_for :users, controllers: {
      sessions: "users/sessions",
      registrations: 'registrations',
      omniauth_callbacks: "users/omniauth_callbacks" 
  }
  resources :users do  
    resources :user_interests
  end

  get 'landings/welcome'
  
  get 'request_applies/index'

  get  'requests/index'  
  get  'requests/new'
  get  'requests/disabled'
  post 'requests/create'
  get  'requests/:id_request' , to:'requests#show' , as:'requests_detail'
  get  'requests/accepted_request', to:'requests#accepted_request' , as:'accepted_request'

  get  'request_applies/accepted_applies'
  post 'request_applies/apply/:id_request', to:'request_applies#new',  as:'apply'

  patch 'request_applies/rechazo_apply/:id_request_apply', to: 'request_applies#revoke_apply', as: 'rechazo'
  post 'request_applies/accept_apply/:id_request_apply', to: 'request_applies#accept_apply', as: 'accept_apply'

  root 'landings#welcome'

end

app/models/request.rb
class Request < ActiveRecord::Base
  belongs_to :user
  belongs_to :interest
  has_many :request_applies
  has_many :users, through: :request_applies 
  

  scope :active_requests, -> { where( state_request:1 ) }  
  scope :accepted_requests, -> { where( state_request:2 ) }  
  scope :active_canceled_requests, -> { where( state_request:3 ) }  
  scope :active_taked_requests, -> { where( state_request:4 ) }  

  #attr_accessor :hour_begin, :hour_end

  before_create :agrega_estado_activo

  def self.all_interesting_request(current_user)
    Request.all.includes(:user)
          .where.not(user_id: current_user.id)
          .joins(:interest)
          .where(interest_id:   
            current_user.interests.pluck("interests.id")
          )
  end

  def self.all_includes_user
    Request.all.includes(:user)
  end



  def self.get_active_request_number
  	return 1
  end

  def self.get_accepted_request_number
  	return 2
  end

  def self.get_canceled_request_number
  	return 3
  end

  def self.get_taked_request_number
  	return 4
  end

  private
    def agrega_estado_activo
      self.state_request = 1
    end

 end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
	before_action :set_request, only: [:show]

	def index
		# Todos los requests exxcepto los del usuario
		#asociados a sus intereses
		@requests = Request.all_includes_user
		
		#@interesting_user_requests = Request.all
		#	.where.not(user_id: current_user.id)
		#	.joins(:interest)
		#	.where(interest_id: 	
		#		current_user.interests.pluck("interests.id")
		#	)
		@interesting_user_requests = Request.all_interesting_request(current_user)	
		#render json:@requests.to_json

		#current_user_interest_ids = current_user.interests.pluck(:id)
		#@user_to_do_requests = Request.where(id: current_user_interest_ids)
		#@interesting_request_count = @interesting_user_requests.count
		@other_requests = @requests - @interesting_user_requests
		#render json:@other_requests.to_json
		#byebug
	end
	def disabled
		@accepted_requests = current_user.requests.where(state_request:2)
	end

	def new
		user_interest = current_user.interests
		interests = Interest.all - user_interest
		@interest_by_importance = user_interest + interests
		@request = Request.new
	end	

	def create

		request = Request.new(request_params)
		request.user = current_user
		#request.date_activity.strftime("%d/%m/%y")

		#byebug
		#date_activity_date = request.date_activity.to_date
		#date_activity_hour = request.date_activity
		byebug
		if request.save
			redirect_to request_applies_index_path
		else
		end
		#byebug				
	end
	def show
		@estado_boton_postulacion = current_user.request_applies.where(request:@request).any?
		@total_postulaciones = @request.request_applies.count	
		@comments = Comment.joins(:request).where("requests.id = ?", @request.id)
		@comment = Comment.new		
	end

	#def accepted_request
	#	@accepted_requests = current_user.request.where(state_request:2)
	#end
	

	private 
		def request_params
      		params.require(:request).permit(:title, :description, :date_activity, :date_activity_end,:interest_id,:time_begin,:time_end)
    	end
    	def set_request
	      @request = Request.find(params[:id_request])
	    end	    
end

app/views/requests/_request.html.erb
	<div id="actividad-<%= request.id%>" class="jumbotron">
	<%= request.id %>
		<h2><strong>Titulo:</strong><%= request.title %></h2>
		<h3><strong>Descripcion:</strong><%= request.description %></h2>
		<p><strong>Dia Inicio:</strong><%= request.date_activity.strftime("%d/%m/%y") %></p>
		<p><strong>Dia fin:</strong><%= request.date_activity_end.strftime("%d/%m/%y") %></p>
		
		
		<p><strong>Lugar:</strong><%= request.location %></p>
		
		<% if request.request_applies.count > 0 %>
			<h2>Hay <%= pluralize(request.request_applies.active_applies.count, 'usuario postulando', 'usuarios postulando') %> a tu actividad</h2>
			<ul>
				<%request.request_applies.active_applies.each do |apply|  %>
					<li><%= apply.user.name %> el id es <%= apply.id %></li>
					<%= link_to 'Rechazar',  rechazo_path(id_request_apply: apply.id), method: :patch %>
					<%= link_to 'Aceptar',  accept_apply_path(id_request_apply: apply.id), method: :post %>
				<% end %>
			</ul>	
		<% else %>
			<h2>No hay postulantes a tu actividad ='(</h2>
		<% end %>

	</div>
	

app/views/requests/create_comment.js.erb
$("#comments").append("<%= j comment.content %></div>");

app/views/requests/index.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title">Actividades Interesantes</h3>
  </div>
  <div class="panel-body">
    <div class="row">
    <% unless @interesting_user_requests.blank? or @interesting_user_requests.nil?%>
       <% @interesting_user_requests.each do |request| %>
         
           <div class="col-sm-6 col-md-4">
             <div class="thumbnail">
               <img src="..." alt="...">
               <div class="caption">
                 <h3><%= request.title %></h3>
                 <h4><%= request.description %></h4>
                 <h5><strong>Creada por:</strong> <%= image_tag(request.user.image) %><%= request.user.name %></h4>
                 <p><strong>Lugar:</strong><%= request.location %></p>
                 <p><strong>Dia y Hora:</strong><%= request.date_activity %></p>        
                 <p><%= link_to 'Detalles', requests_detail_path(request), :class=>"btn btn-primary"%>
                 </p>
               </div>
             </div>
           </div>
         
       <% end %>
    <% else %>
    <strong>
      <div class="alert alert-warning" role="alert">        
        <%= link_to 'No tienes intereses asociados, selecciona algun interes', user_user_interests_path(current_user.id) ,:class=>"alert-link"%>
      </div>
      </strong>
    <% end %>
    </div>
  </div>
  <div class="panel-footer"></div>
</div>

<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title">Otras actividades</h3>
  </div>
  <div class="panel-body">
    <div class="row">
       <% @other_requests.each do |other_request| %>
        <div class="col-sm-6 col-md-4">
          <div class="thumbnail">
            <img src="..." alt="...">
            <div class="caption">
              <h3><%= other_request.title %></h3>
              <h4><%= other_request.description %></h4>
              <h5><strong>Creada por:</strong> <%= image_tag(other_request.user.image) %><%= other_request.user.try(:name) %></h4>
              <p><strong>Lugar:</strong><%= other_request.location %></p>
              <p><strong>Dia y Hora:</strong><%= other_request.date_activity %></p>        
              <p><%= link_to 'Detalles', requests_detail_path(other_request), :class=>"btn btn-primary"%></button>
              </p>
            </div>
          </div>
        </div>
       <% end %>
     </div>
  </div>
  <div class="panel-footer"></div>

      

app/views/requests/new.html.erb
<h1>Crea una nueva actividad</h1>

<%= form_for @request, class: "form-horizontal", url: {action: "create"} do |f| %>
<div class="form-group">	
  <%=f.label :interest_id, "Interest", class: "col-md-4 control-label" %>
  <%= f.select :interest_id, options_from_collection_for_select(@interest_by_importance, "id", "name"), class: "form-control" %>
 </div>
 <div class="form-group">
	 <%= f.label :title , class: "col-sm-2 control-label" %>
	 <div class="col-sm-10">
	  <%= f.text_field :title , class:"form-control"%>
	  </div>
  </div>
  <div class="form-group">
	  <%= f.label :description , class: "col-sm-2 control-label" %>
	  <div class="col-sm-10">
	  <%= f.text_area :description, size: "3x3",class:"form-control " %>
	  </div>
  </div>
  <div class="form-group">
  	<div class="col-sm-2">
	  <%= f.label :date_activity %>	  
	 </div>
	  <div class="col-sm-10">
	  	<%= f.date_field(:date_activity) %>
	  	<%= f.time_select(:time_begin) %>
	  </div>
  </div>
  <div class="form-group">
  	  <div class="col-sm-2">	
	  <%= f.label :date_activity_end %>
	  </div>
	  <div class="col-sm-10">
	  	<%= f.date_field(:date_activity_end) %>
	  	<%= f.time_select(:time_end) %>
	  </div>
  </div>    
  <div class="col-sm-10 col-sm-offset-2">
  <%= f.submit "Crear actividad" , class: "btn btn-default btn-primary"%>
  </div>
<% end %>

app/views/requests/show.html.erb
<div>
  <h4><%= @request.user.name %></h2>
  <h2><%= @request.title %></h3>
  <h3><%= @request.description%></h3>
  <h3><%= @request.interest.name %></h3>  
  <h3>Lugar: <%= @request.location %></h3>
  <h3><%= @request.date_activity %></h3>
  <h3><%= @request.date_activity_end %></h3>
</div>
</br>
<div>
el estado!!!!<%=  @estado_boton_postulacion %>
  <div class="postular">
    <% unless @estado_boton_postulacion%>
      <button class="btn btn-success"><%= link_to 'Postula a esta actividad!' , apply_path(@request),  method: :post %></button></div>
    <% else %>
      <button class="btn btn-alert" disabled="disabled"> Ya postulaste a esta actividad</button></div>
    <% end %>
    
  <div> <%= pluralize(@total_postulaciones, 'usuario postulando a esta actividad', 'usuarios postulando a esta actividad')  %></div>
  <div class="user_foto">
    fotito
  </div> 
</div>
<%= render 'comments/form' %>

 <%= render 'comments/index'%>  