config/routes.rb
Rails.application.routes.draw do
  resources :comments
  get 'dashboard/index'

  get 'users/index'

  devise_for :users, controllers: {
      sessions: "users/sessions",
      registrations: 'registrations',
      omniauth_callbacks: "users/omniauth_callbacks" 
  }
  resources :users do  
    resources :user_interests
  end

  get 'landings/welcome'
  
  get 'request_applies/index'

  get  'requests/index'  
  get  'requests/new'
  get  'requests/disabled'
  post 'requests/create'
  get  'requests/:id_request' , to:'requests#show' , as:'requests_detail'
  get  'requests/accepted_request', to:'requests#accepted_request' , as:'accepted_request'

  get  'request_applies/accepted_applies'
  post 'request_applies/apply/:id_request', to:'request_applies#new',  as:'apply'

  patch 'request_applies/rechazo_apply/:id_request_apply', to: 'request_applies#revoke_apply', as: 'rechazo'
  post 'request_applies/accept_apply/:id_request_apply', to: 'request_applies#accept_apply', as: 'accept_apply'

  root 'landings#welcome'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @title %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</head>
<body>
<div class="container">
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">DoIt!</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
       
        <%if signed_in? %>        
        
        <li><%= link_to 'Home', requests_index_path %></li>
        <li><%= link_to 'Crear Actividad', requests_new_path %></li>
        <% else %>
         
         <li><%= link_to 'Home', new_user_session_path %></li> 
         <li><%= link_to 'Crear Actividad', new_user_session_path %></li>
        <% end %>
        
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">       
        <li class="dropdown">
          <%if signed_in? %> 
          <li><%= link_to 'Mis actividades', request_applies_index_path %></li>        
          <li><%= link_to 'Mis Postulaciones', new_user_session_path %></li>        
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= image_tag(current_user.image) %> <%= current_user.name %> <span class="caret"></span></a>
            <ul class="dropdown-menu">           
            <li><%= link_to 'Añadir Intereses', user_user_interests_path(current_user.id) %></li>
            <li><%= link_to 'Total de actividades x dias', dashboard_index_path %></li        
            
              <li role="separator" class="divider"></li>
              <li><%= link_to "Salir", destroy_user_session_path, method: :delete %></li>
              <li role="separator" class="divider"></li>
              
            </ul>
            <% else %>
              <li><%= link_to 'Ingresar', new_user_session_path %></li>

            <%end %>
        </li>
        
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
<%= yield %>	
</div>
 


</body>
<script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '357802794608945',
      xfbml      : true,
      version    : 'v2.7'
    });
  };

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "//connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));

  
</script>

</html>